[package]
name = "rise"
version = "0.1.0"
authors = ["Michel Steuwer <michel.steuwer@glasgow.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
